### ISSUE TITLE
Missing error message for when voice channel isn't specified

### ISSUE THREAD

**Issue by ttocsneb** [MemeMasters/Misaka-Mikoto-Meme-Machine-100-567#8]
I can't seem to get the bot to join voice channels without an error.  There must be something I may have accidentally changed, but I can't tell what.

Here is a traceback of the error

    Ignoring exception in command join
    Traceback (most recent call last):
      File "E:\Benjamin\Documents\git\dnd_bot\venv\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
        yield from command.invoke(ctx)
      File "E:\Benjamin\Documents\git\dnd_bot\venv\lib\site-packages\discord\ext\commands\core.py", line 367, in invoke
        yield from self.prepare(ctx)
      File "E:\Benjamin\Documents\git\dnd_bot\venv\lib\site-packages\discord\ext\commands\core.py", line 345, in prepare
        yield from self._parse_arguments(ctx)
      File "E:\Benjamin\Documents\git\dnd_bot\venv\lib\site-packages\discord\ext\commands\core.py", line 313, in _parse_arguments
        kwargs[name] = yield from self.transform(ctx, param)
      File "E:\Benjamin\Documents\git\dnd_bot\venv\lib\site-packages\discord\ext\commands\core.py", line 212, in transform
        raise MissingRequiredArgument('{0.name} is a required argument that is missing.'.format(param))
    discord.ext.commands.errors.MissingRequiredArgument: channel is a required argument that is missing.

There is nothing in our code that is in the traceback, so I don't know what type of error would be causing it.

The error has started heppening after I moved the Voice class to its own module at 456ab342dd28c55e3bfd813321cf6fe7217c8c8c in the  [`devel`](https://github.com/MemeMasters/Misaka-Mikoto-Meme-Machine-100-567/commits/devel) branch

**Comment by ttocsneb** [comment]
Nevermind.  The bug was caused by not giving a channel to join.

This should, however, be accounted for, and print an error when someone does this
